"""
JournalAgent — Documents every step, result, and decision in structured markdown journals.
Maintains research journal, strategy logs, backtest results, and configuration changes.
"""
import os
import json
import logging
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional

BASE_DIR = Path(__file__).parent.parent.parent
JOURNAL_DIR = BASE_DIR / "journal"
CONFIG_CHANGE_LOG = JOURNAL_DIR / "config_change_log.md"

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s',
    handlers=[logging.FileHandler(Path(__file__).parent.parent / 'logs' / 'journal_agent.log'), logging.StreamHandler()]
)
logger = logging.getLogger(__name__)


class JournalAgent:
    """Maintains all system documentation and journals."""

    def __init__(self, orchestrator=None):
        self.orchestrator = orchestrator
        self.buffer = []
        self.journal_dir = JOURNAL_DIR
        self._ensure_journal_structure()
        logger.info("JournalAgent initialized")

    def _ensure_journal_structure(self):
        """Ensure all required journal directories and files exist."""
        self.journal_dir.mkdir(parents=True, exist_ok=True)
        (self.journal_dir / "strategies").mkdir(exist_ok=True)
        (self.journal_dir / "backtest_results").mkdir(exist_ok=True)
        (self.journal_dir / "review_reports").mkdir(exist_ok=True)

        overview = self.journal_dir / "00_research_overview.md"
        if not overview.exists():
            overview.write_text("# BankNifty Options Trading — Research Overview\n\n"
                               "**Last Updated:** " + datetime.now().isoformat() + "\n\n"
                               "## Mission\nAutonomous multi-agent research and algo development system for BankNifty options trading.\n\n"
                               "## Phase Status\n- [ ] Phase 1: Project Scaffolding\n"
                               "- [ ] Phase 2: Data Collection\n"
                               "- [ ] Phase 3: Strategy Research\n"
                               "- [ ] Phase 4: Backtesting\n"
                               "- [ ] Phase 5: Review & Ranking\n"
                               "- [ ] Phase 6: Algo System Build\n"
                               "- [ ] Phase 7: Config-Driven Updates\n"
                               "- [ ] Phase 8: Live Simulation\n"
                               "- [ ] Phase 9: Dashboard\n")

    def write_data_collection_report(self, data_sources: List[str], summary: Dict,
                                      date_range: str, quality_metrics: Dict):
        """Write data collection documentation."""
        report = f"""# Phase 2: Data Collection Report

**Timestamp:** {datetime.now().isoformat()}
**Date Range:** {date_range}

## Data Sources Used

| Source | Status | Notes |
|--------|--------|-------|
"""
        for source in data_sources:
            status = "✅ Success" if source != "synthetic" else "⚠️ Synthetic (fallback)"
            report += f"| {source} | {status} | Generated due to primary source unavailability |\n"

        report += f"""
## Data Quality Metrics

| Metric | Value |
|--------|-------|
| Total OHLCV records | {summary.get('ohlcv', 'N/A')} |
| Options chain records | {summary.get('options_chain', 'N/A')} |
| VIX records | {summary.get('vix', 'N/A')} |
| Date range | {summary.get('ohlcv_range', 'N/A')} |

## Features Generated

- OHLCV: open, high, low, close, volume (1-min, 5-min, 15-min, hourly, daily)
- Options Greeks: delta, gamma, theta, vega, IV
- OI and OI change per strike
- PCR time series
- IV rank and IV percentile

## Sample Statistics

(To be populated from actual data analysis)

---
*Generated by JournalAgent*
"""
        report_path = self.journal_dir / "01_data_collection.md"
        with open(report_path, 'w') as f:
            f.write(report)
        logger.info(f"Data collection report written to {report_path}")

    def write_strategy_journal(self, strategy_id: str, strategy_data: Dict):
        """Write or update strategy research journal."""
        strategy_dir = self.journal_dir / "strategies" / strategy_id
        strategy_dir.mkdir(parents=True, exist_ok=True)

        overview = f"""# {strategy_data.get('name', strategy_id)} — Research Overview

**Strategy ID:** {strategy_id}
**Documented:** {datetime.now().isoformat()}

## Hypothesis

{strategy_data.get('hypothesis', 'See individual approaches')}

## Approaches

"""
        for approach in strategy_data.get('approaches', []):
            approach_file = strategy_dir / f"{approach['id']}_results.md"
            ap_content = f"""# Approach {approach['id'].upper()}: {approach['name']}

**Status:** Documented

## Hypothesis
{approach['hypothesis']}

## Entry Rules
{chr(10).join(f'{i+1}. {r}' for i, r in enumerate(approach.get('entry_rules', [])))}

## Exit Rules
{chr(10).join(f'{i+1}. {r}' for i, r in enumerate(approach.get('exit_rules', [])))}

## Risk Rules
{chr(10).join(f'{i+1}. {r}' for i, r in enumerate(approach.get('risk_rules', [])))}

## Indicators
{', '.join(approach.get('indicators', []))}

## Expected Market Conditions
- **Works in:** {approach.get('expected_market', 'N/A')}
- **Fails in:** {approach.get('failure_market', 'N/A')}

## Backtest Results
(To be populated after backtesting)
"""
            with open(approach_file, 'w') as f:
                f.write(ap_content)
            overview += f"- [{approach['id'].upper()}]({approach['id']}_results.md): {approach['name']}\n"

        overview_path = strategy_dir / "overview.md"
        with open(overview_path, 'w') as f:
            f.write(overview)
        logger.info(f"Strategy journal written for {strategy_id}")

    def write_backtest_result(self, strategy_id: str, approach_id: str, results: Dict):
        """Write backtest result documentation."""
        strategy_dir = self.journal_dir / "strategies" / strategy_id
        strategy_dir.mkdir(parents=True, exist_ok=True)

        stats = results.get('statistics', {})
        report = f"""# Backtest Results: {strategy_id}/{approach_id.upper()}

**Backtest Period:** {results.get('start_date', 'N/A')} to {results.get('end_date', 'N/A')}
**Completed:** {datetime.now().isoformat()}

## Performance Statistics

| Metric | Value |
|--------|-------|
| Total Trades | {stats.get('total_trades', 0)} |
| Win Rate | {stats.get('win_rate', 0)*100:.1f}% |
| Sharpe Ratio | {stats.get('sharpe_ratio', 0):.3f} |
| Max Drawdown | {stats.get('max_drawdown_pct', 0):.2f}% |
| Profit Factor | {stats.get('profit_factor', 0):.2f} |
| Average Trade P&L | ₹{stats.get('avg_trade', 0):.2f} |
| Total P&L | ₹{stats.get('total_pnl', 0):.2f} |
| Open Positions | {stats.get('open_positions', 0)} |
| Margin Used | ₹{stats.get('margin_used', 0):.2f} |

## Trade Log
(Trades saved to: backtests/results/{strategy_id}_{approach_id}/)

## Equity Curve
(Equity curve data saved to: backtests/results/{strategy_id}_{approach_id}/equity_curve.csv)

---
*Generated by JournalAgent*
"""
        report_path = strategy_dir / f"{approach_id}_backtest.md"
        with open(report_path, 'w') as f:
            f.write(report)
        logger.info(f"Backtest result written for {strategy_id}/{approach_id}")

    def write_config_change(self, param: str, old_value: any, new_value: any, reason: str):
        """Log a configuration change."""
        if not CONFIG_CHANGE_LOG.exists():
            CONFIG_CHANGE_LOG.write_text("# Configuration Change Log\n\n"
                                        "| Timestamp | Parameter | Old Value | New Value | Reason |\n"
                                        "|------------|-----------|-----------|-----------|--------|\n")

        timestamp = datetime.now().isoformat()
        with open(CONFIG_CHANGE_LOG, 'a') as f:
            f.write(f"| {timestamp} | {param} | {old_value} | {new_value} | {reason} |\n")
        logger.info(f"Config change logged: {param} = {new_value} (was {old_value})")

    def update_research_overview(self, phase: int, status: str, details: str = ""):
        """Update the research overview file."""
        overview = self.journal_dir / "00_research_overview.md"
        if overview.exists():
            content = overview.read_text()
            marker = f"- [ ] Phase {phase}:"
            if marker in content:
                content = content.replace(marker, f"- [x] Phase {phase}: {status}")
                if details:
                    content = content.replace(f"Phase {phase}: {status}", f"Phase {phase}: {status} — {details}")
                overview.write_text(content)

    def write_approved_strategy(self, strategy_id: str, approach_id: str,
                                 final_stats: Dict, config: Dict):
        """Write final approved strategy documentation."""
        report = f"""# Approved Strategy

**Strategy:** {strategy_id}/{approach_id}
**Approved:** {datetime.now().isoformat()}

## Final Performance Statistics

| Metric | Value |
|--------|-------|
| Sharpe Ratio | {final_stats.get('sharpe_ratio', 0):.3f} |
| Win Rate | {final_stats.get('win_rate', 0)*100:.1f}% |
| Max Drawdown | {final_stats.get('max_drawdown_pct', 0):.2f}% |
| Profit Factor | {final_stats.get('profit_factor', 0):.2f} |
| Total P&L | ₹{final_stats.get('total_pnl', 0):.2f} |

## Configuration

```yaml
strategy_id: {config.get('strategy_id', strategy_id)}
approach_id: {config.get('approach_id', approach_id)}
stop_loss: {config.get('stop_loss', 'TBD')}
target: {config.get('target', 'TBD')}
max_positions: {config.get('max_positions', 3)}
lot_size: {config.get('lot_size', 15)}
```

## Live Trading Notes

(To be populated after Phase 8 validation)

---
*Generated by JournalAgent*
"""
        report_path = self.journal_dir / "approved_strategy.md"
        with open(report_path, 'w') as f:
            f.write(report)
        logger.info(f"Approved strategy documented: {strategy_id}/{approach_id}")

    def handle_message(self, message: dict):
        """Handle incoming messages from other agents."""
        msg_type = message.get("type", "")
        payload = message.get("payload", {})

        if msg_type == "DATA_READY":
            self.write_data_collection_report(
                payload.get("data_sources", []),
                payload.get("summary", {}),
                payload.get("date_range", "N/A"),
                payload.get("quality_metrics", {})
            )
            self.update_research_overview(2, "Complete", f"Data sources: {', '.join(payload.get('data_sources', []))}")

        elif msg_type == "RESEARCH_COMPLETE":
            self.update_research_overview(3, "Complete", f"{payload.get('strategies_count', 0)} strategies documented")

        elif msg_type == "BACKTEST_COMPLETE":
            self.write_backtest_result(
                payload.get("strategy", ""),
                payload.get("approach", ""),
                payload.get("results", {})
            )

        elif msg_type == "REVIEW_COMPLETE":
            self.update_research_overview(5, "Complete", "Strategy ranking complete")

        logger.info(f"JournalAgent handled message: {msg_type}")


if __name__ == "__main__":
    agent = JournalAgent()
    print("JournalAgent ready.")